// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmEAiEI2UgHy1yMUBUIcbv1Npjcz4hMkA',
    appId: '1:668683233484:android:d909864cc171a6d9bb7a69',
    messagingSenderId: '668683233484',
    projectId: 'protective-garment',
    databaseURL: 'https://protective-garment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'protective-garment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-tFIUsyCk_7ElDiFIgPKEe-55UC4Wj6I',
    appId: '1:668683233484:ios:b24c5ad9c9c1e95dbb7a69',
    messagingSenderId: '668683233484',
    projectId: 'protective-garment',
    databaseURL: 'https://protective-garment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'protective-garment.appspot.com',
    iosClientId: '668683233484-is3jf3gcluiou4rrv8b22le58e847hcf.apps.googleusercontent.com',
    iosBundleId: 'com.af.protectiveclothing.protectiveClothing',
  );
}
